controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . 2 . . . . . . . . 
        . . . . . . 2 1 2 . . . . . . . 
        . . 2 2 . . 2 1 2 . . 2 2 . . . 
        . . 2 1 2 . 2 1 2 2 2 1 2 . . . 
        . . . 2 1 2 2 1 2 2 1 2 . . . . 
        . 2 2 2 2 1 2 1 1 1 2 . . . . . 
        2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 . 
        . 2 2 2 2 2 1 1 1 1 1 1 1 1 1 2 
        . . . . . 2 1 1 1 2 2 2 2 2 2 . 
        . . . . 2 1 2 1 2 1 2 . . . . . 
        . . . 2 1 2 2 1 2 2 1 2 . . . . 
        . . 2 1 2 . 2 1 2 . 2 1 2 . . . 
        . . 2 2 . . 2 1 2 . . 2 2 . . . 
        . . . . . . 2 1 2 . . . . . . . 
        . . . . . . 2 1 2 . . . . . . . 
        . . . . . . . 2 . . . . . . . . 
        `, plan, 50, 0)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 500)
    projectile.destroy()
    info.changeScoreBy(1e+21)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    plan2.destroy(effects.trail, 500)
    scene.cameraShake(4, 500)
    info.changeLifeBy(-1)
})
let plan2: Sprite = null
let projectile: Sprite = null
let plan: Sprite = null
plan = sprites.create(img`
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    .............ffff...
    ......fff...ffffff..
    ......ffffffffffff..
    ......ffffffffffff..
    .......ff...ffffff..
    .............ffff...
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
controller.moveSprite(plan)
plan.setStayInScreen(true)
info.setLife(1000000000)
game.onUpdateInterval(500, function () {
    plan2 = sprites.create(img`
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ...555ddd...........
        .45555ddddd.5d......
        .45555ddddd45d......
        .45555ddddd455......
        .45555ddddd.55......
        ...555ddd...........
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        ....................
        `, SpriteKind.Enemy)
    plan2.setVelocity(-50, 0)
    plan2.setPosition(160, randint(5, 115))
    plan2.setFlag(SpriteFlag.AutoDestroy, true)
})
